# -*- coding: utf-8 -*-
"""4IK25CS190_EXP_01

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1g8IkhPofqr1tvnkIR3Nl744PtN0fwGNn
"""

print("Welcome to Data Analytics and Visualisation")

import pandas as pd
import numpy as np

print("Numpy version: ",np.__version__)
print("Pandas version: ",pd.__version__)

marks = np.array([78,85,92,67,88])
print("Marks: ",marks)
print("Type: ",type(marks))

print("Number of dimensions: ",marks.ndim)
print("Shape: ",marks.shape)
print("Number of elements: ",marks.size)

print("Original: ",marks)
print("Add 5: ",marks+5)
print("Multiply by 2: ",marks*2)
print("Divide by 2: ",marks/2)
print("Square: ",marks**2)

print("Sum: ",marks.sum())
print("Mean: ",marks.mean())
print("Maximum: ",marks.max())
print("Minimum: ",marks.min())

print("First marks: ",marks[0])
print("Second marks: ",marks[1])
print("Last marks: ",marks[-1])

print("Index 1 to 3: ",marks[1:4])
print("First three: ",marks[:3])
print("From index 2: ",marks[2:])
print("Every second element: ",marks[::2])

student_marks = np.array([
    [78,85,92],
    [67,88,76],
    [90,95,89]
    ])
print(student_marks)
print(student_marks.shape)

print("Mean of all values: ",student_marks.mean())
print("Column wise mean: ",student_marks.mean(axis=0))
print("Row wise mean: ",student_marks.mean(axis=1))

data = {
    "Name": ["Anu","Rahul","Kiran","Priya"],
    "Branch": ["CSE","AIML","CSE","AIML"],
    "Marks": [85,91,76,88]
}
df = pd.DataFrame(data)
df

print("Shape",df.shape)
print("\nColumns")
print(df.columns)

df.head()

df.tail()

df.info()

df.describe()

print("Marks column:")
print(df["Marks"])
print("\nBranch and Marks column:")
print(df[["Branch","Marks"]])

print("First row:")
print(df.iloc[0])#iloc is for integer location based indexing
print("\nSecond row:")
print(df.iloc[1])
print("\nFirst three rows:")
print(df.iloc[0:3])
print("\nFirst two rows and first 2 columns:")
print(df.iloc[0:2,0:2])

print("First three rows:")
display(df.iloc[0:3])
print("\nRows 1 to 3 Name and Marks:")
display(df.iloc[1:4,0:3])

high_scorers = df[df["Marks"]>90]
high_scorers

print("Students from CSE:")
display(df[df["Branch"] == "CSE"])

print("\nStudents scoring 85 or above:")
display(df[df["Marks"] >= 85])

stud_data = {
    "Name": ["Anu","Rahul","Kiran","Priya","Shweta"],
    "Department": ["CSE","AIML","CSE","AIML","CSE"],
    "Marks": [85,91,76,88,92],
    "Attendance": [91,90,22,12,90]
}
df = pd.DataFrame(stud_data)
df

display(df[["Name","Marks"]])
print("\nStudents scoring 80 or above:")
display(df[df["Marks"] >= 80])
print("\nStudents attending 85% or above:")
display(df[df["Attendance"] >= 85])
print("\nFirst three students:")
display(df.iloc[0:3])
print("\nAverage Marks: ",df["Marks"].mean())
print("\nMaximum Marks: ",df["Marks"].max())
print("\nStudents from CSE:")
display(df[df["Department"] == "CSE"])
print("\n")
display(df[(df["Marks"] > 80) & (df["Attendance"]> 85)])













