# -*- coding: utf-8 -*-
"""4IK25CS190_EXP-02

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZtGdn2fw865FhnXwsEQVYJxc44M2L5Ts
"""

import pandas as pd
import numpy as np

data={'Name':['Amit','Bebo','Chetan','Amit','Divya','Ravi','Sneha','Karan',
              'Pooja','Manish','Anjali','Suresh','Kavya','Rahul','Meera',
              'Vikram','Nisha','Arjun','Divya','Rohit','Swathi','Naveen',
              'Priya','Karan','Deepa'],
      'Age':[25,np.nan,30,25,28,22,24,np.nan,27,26,23,29,np.nan,
             25,22,28,24,np.nan,28,26,23,30,27,np.nan,25],
      'Marks':[85,90,np.nan,85,78,95,88,72,np.nan,91,67,84,79,
               np.nan,93,88,76,82,78,np.nan,90,85,71,72,89],
      'City':['Mysuru','Mysuru','Bangaluru','Mysuru',np.nan,'Delhi','Mysuru',
              'Mangalore','Bangaluru',np.nan,'Mysuru','Hubali','Mangalore',
              'Delhi','Bangaluru',np.nan,'Mysuru','Hubali',np.nan,'Delhi',
              'Mangalore','Mysuru','Bangaluru','Mangalore','Hubali']
     }
df = pd.DataFrame(data)
print("Dataset:")
print(df)

print("\nShape of dataset (rows, columns):",df.shape)

print("\nColumn names:",df.columns.tolist())

print("\nData types of each column:")
print(df.dtypes)

print("\nDataset Info:")
df.info()

print("\nDescriptive statistics (numerical columns):")
print(df.describe())

print("\nMean:\n",df.mean(numeric_only=True))

print("\nMedian:\n",df.median(numeric_only=True))

print("\nStandard Deviation:\n",df.std(numeric_only=True))

print("\nMissing values in each column:")
print(df.isnull().sum())
print("\nTotal missing values in dataset:",df.isnull().sum().sum())

print("\nDuplicate rows in dataset:")
print(df[df.duplicated()])
print("\nNumber of duplicate rows:",df.duplicated().sum())
print("\nEDA process completed successfully!")



